import type { FactorDefinition } from "@/lib/domain/types";

const numberFactor = (
  key: string,
  name: string,
  category: FactorDefinition["category"],
  unit: string,
  description: string,
  aggregationMethod: FactorDefinition["aggregationMethod"] = "MEAN",
): FactorDefinition => ({
  id: `factor-${key}`,
  key,
  name,
  category,
  dataType: "NUMBER",
  unit,
  description,
  aggregationMethod,
  active: true,
});

export const BASELINE_FACTORS: readonly FactorDefinition[] = [
  numberFactor("latitude", "Latitude", "AREA", "degree", "Area latitude", "LAST"),
  numberFactor("longitude", "Longitude", "AREA", "degree", "Area longitude", "LAST"),
  numberFactor("elevation_m", "Elevation", "AREA", "m", "Area elevation", "LAST"),
  {
    id: "factor-soil_type",
    key: "soil_type",
    name: "Soil type",
    category: "SOIL",
    dataType: "CATEGORY",
    description: "Soil classification",
    aggregationMethod: "LAST",
    active: true,
  },
  numberFactor("soil_ph", "Soil pH", "SOIL", "pH", "Soil acidity/alkalinity", "LAST"),
  numberFactor("sand_pct", "Sand percentage", "SOIL", "%", "Soil sand percentage", "LAST"),
  numberFactor("silt_pct", "Silt percentage", "SOIL", "%", "Soil silt percentage", "LAST"),
  numberFactor("clay_pct", "Clay percentage", "SOIL", "%", "Soil clay percentage", "LAST"),
  numberFactor(
    "organic_matter_pct",
    "Organic matter",
    "SOIL",
    "%",
    "Soil organic matter percentage",
    "LAST",
  ),
  {
    id: "factor-drainage_class",
    key: "drainage_class",
    name: "Drainage class",
    category: "SOIL",
    dataType: "CATEGORY",
    description: "Soil drainage classification",
    aggregationMethod: "LAST",
    active: true,
  },
  numberFactor(
    "water_holding_capacity",
    "Water holding capacity",
    "SOIL",
    "%",
    "Estimated soil water holding capacity",
    "LAST",
  ),
  numberFactor("slope_degree", "Slope", "SOIL", "degree", "Area slope", "LAST"),
  numberFactor("temperature_min_c", "Minimum temperature", "WEATHER", "°C", "Daily minimum temperature", "MIN"),
  numberFactor("temperature_max_c", "Maximum temperature", "WEATHER", "°C", "Daily maximum temperature", "MAX"),
  numberFactor("temperature_avg_c", "Average temperature", "WEATHER", "°C", "Daily average temperature"),
  numberFactor("rainfall_mm", "Rainfall", "WEATHER", "mm", "Daily rainfall", "SUM"),
  numberFactor(
    "relative_humidity_pct",
    "Relative humidity",
    "WEATHER",
    "%",
    "Daily relative humidity",
  ),
  numberFactor(
    "soil_moisture_pct",
    "Soil moisture",
    "SOIL",
    "%",
    "Soil moisture percentage when available",
  ),
  numberFactor("solar_radiation", "Solar radiation", "WEATHER", "MJ/m²", "Daily solar radiation"),
  numberFactor("wind_speed_mps", "Wind speed", "WEATHER", "m/s", "Daily wind speed"),
  {
    id: "factor-planting_date",
    key: "planting_date",
    name: "Planting date",
    category: "CROP",
    dataType: "TEXT",
    unit: "date",
    description: "Cultivation planting date",
    aggregationMethod: "LAST",
    active: true,
  },
  numberFactor("expected_harvest_days", "Expected harvest days", "CROP", "day", "Configured growing duration", "LAST"),
  numberFactor("planting_density", "Planting density", "MANAGEMENT", "plant/m²", "Plants per area", "LAST"),
  numberFactor("irrigation_amount", "Irrigation amount", "MANAGEMENT", "mm", "Applied irrigation", "SUM"),
  numberFactor("nitrogen_amount", "Nitrogen amount", "MANAGEMENT", "kg/rai", "Applied nitrogen", "SUM"),
  numberFactor("phosphorus_amount", "Phosphorus amount", "MANAGEMENT", "kg/rai", "Applied phosphorus", "SUM"),
  numberFactor("potassium_amount", "Potassium amount", "MANAGEMENT", "kg/rai", "Applied potassium", "SUM"),
] as const;

export function findFactor(factorKey: string) {
  return BASELINE_FACTORS.find(
    (factor) => factor.key === factorKey && factor.active,
  );
}
